services:
  - type: web
    name: medusa-api
    env: node
    plan: free
    buildCommand: cd admin && yarn install && yarn build
    startCommand: cd admin && yarn start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: postgres://marketplace_postgres:Vu]Q"<F^^G2@\sE3@omnibot.cloud:5433/scripts_marketplace
      - key: MEDUSA_ADMIN_DISABLE
        value: true
      - key: MEDUSA_ADMIN_SERVE
        value: false
      - key: MEDUSA_ADMIN_AUTO_REBUILD
        value: false
      - key: JWT_SECRET
        value: your-super-secret-jwt-key-change-this-in-production
      - key: COOKIE_SECRET
        value: your-super-secret-cookie-key-change-this-in-production
      - key: STORE_CORS
        value: "*"
      - key: ADMIN_CORS
        value: "*"